### ISSUE TITLE
Error while setting platform: timetree as calendar

### ISSUE THREAD

**Issue by barnagoz** [Micha95/homeassistant_timetree_calendar#1]
Hi!

Unfortunately, when I tried to install the "add-on", I got this error message: 
```
2021-10-23 19:36:33 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up timetree platform for calendar
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/timetree/calendar.py", line 38, in setup_platform
EntitiesCalendarDevice(
File "/config/custom_components/timetree/calendar.py", line 55, in __init__
self.data = EntitiesCalendarData(
File "/config/custom_components/timetree/calendar.py", line 114, in __init__
self._entities = timetree_object.get_upcoming_events(self._calendar.id, 'Europe/Berlin', 7).data
File "/config/custom_components/timetree/timetree_sdk/api.py", line 83, in get_upcoming_events
return EventResponse.new_from_json_dict(response.json())
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
return cls(**d)
File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 152, in __init__
self.data = [self.get_or_new_from_json_dict(it, EventDataResponse) for it in data]
File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 152, in <listcomp>
self.data = [self.get_or_new_from_json_dict(it, EventDataResponse) for it in data]
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 18, in get_or_new_from_json_dict
return cls.new_from_json_dict(data)
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
return cls(**d)
File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 164, in __init__
self.attributes = self.get_or_new_from_json_dict(attributes, EventAttributes)
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 18, in get_or_new_from_json_dict
return cls.new_from_json_dict(data)
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
return cls(**d)
TypeError: __init__() got an unexpected keyword argument 'location_lat'
```

Can you please help with it?

Thanks!

**Comment by llewellynhughes** [comment]
Hi @barnabasgoz 

I came across the same issue, looks like 2 new attributes have been added to events at TimeTree.

To get this to work I edited the following:-
file: timetree_sdk/models/events.py
from:
class EventAttributes(Base):
    def __init__(self, title=None, category=None, all_day=None, start_at=None, start_timezone=None, end_at=None, end_timezone=None, description=None, location=None, url=None, relationships=None):

        super(EventAttributes, self).__init__()

        self.title = title
        self.category = category
        self.all_day = all_day
        self.start_at = start_at
        self.start_timezone = start_timezone
        self.end_at = end_at
        self.end_timezone = end_timezone
        self.description = description
        self.location = location
        self.url = url
        self.label = self.get_or_new_from_json_dict(relationships, EventRelationships)

to:
class EventAttributes(Base):
    def __init__(self, title=None, category=None, all_day=None, start_at=None, start_timezone=None, end_at=None, end_timezone=None, description=None, location=None, url=None, relationships=None, location_lat=None, location_lon=None):

        super(EventAttributes, self).__init__()

        self.title = title
        self.category = category
        self.all_day = all_day
        self.start_at = start_at
        self.start_timezone = start_timezone
        self.end_at = end_at
        self.end_timezone = end_timezone
        self.description = description
        self.location = location
        self.url = url
        self.location_lat = location_lat
        self.location_lon = location_lon
        self.label = self.get_or_new_from_json_dict(relationships, EventRelationships)



and file: timetree_sdk/models/responses.py
from:
class EventAttributes(Base):
    def __init__(self, category=None, title=None, all_day=None, start_at=None, start_timezone=None, end_at=None, end_timezone=None, recurrence=None, recurring_uuid=None, description=None, location=None, url=None, updated_at=None, created_at=None):

        super(EventAttributes, self).__init__()

        self.category = category
        self.title = title
        self.all_day = all_day
        self.start_at = start_at
        self.start_timezone = start_timezone
        self.end_at = end_at
        self.end_timezone = end_timezone
        self.recurrence = recurrence
        self.recurring_uuid = recurring_uuid
        self.description = description
        self.location = location
        self.url = url
        self.updated_at = updated_at
        self.created_at = created_at

to:
class EventAttributes(Base):
    def __init__(self, category=None, title=None, all_day=None, start_at=None, start_timezone=None, end_at=None, end_timezone=None, recurrence=None, recurring_uuid=None, description=None, location=None, url=None, updated_at=None, created_at=None, location_lat=None, location_lon=None):

        super(EventAttributes, self).__init__()

        self.category = category
        self.title = title
        self.all_day = all_day
        self.start_at = start_at
        self.start_timezone = start_timezone
        self.end_at = end_at
        self.end_timezone = end_timezone
        self.recurrence = recurrence
        self.recurring_uuid = recurring_uuid
        self.description = description
        self.location = location
        self.url = url
        self.location_lat = location_lat
        self.location_lon = location_lon
        self.updated_at = updated_at
        self.created_at = created_at

If you need any more info just let me know.

Cheers

**Comment by barnagoz** [comment]
Hi! Thanks for the reply! I will try it tomorrow!

**Comment by verne2021** [comment]
Hi, 
I got this error massage.
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/timetree/calendar.py", line 34, in setup_platform
    calendars = timetree_object.get_calendars()
AttributeError: 'str' object has no attribute 'get_calendars'`


Can you please help with it?

Thanks!

**Comment by necroxysONE** [comment]
Hi @llewellynhughes, 

After making all the changes you suggested (I was having the same issue), here's what comes next:

> Update for calendar.horaire_de_travail fails
>
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
>     raise exc
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/timetree/calendar.py", line 74, in update
>     self.data.update()
>   File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 195, in wrapper
>     result = method(*args, **kwargs)
>   File "/config/custom_components/timetree/calendar.py", line 148, in update
>     start = entity.attributes.start_at
> AttributeError: 'EventAttributes' object has no attribute 'start_at'


Thanks for your help :)

**Comment by llewellynhughes** [comment]
Hi @necroxysONE,

I'll try my best to help! What does your class EventAttributes(base) section look like in timetree_sdk/models/responses.py file and timetree_sdk/models/events.py look like now? it looks like it can't get the start_at attribute in that class in one of those files.

Cheers,

Barry

**Comment by necroxysONE** [comment]
Hi, thank you for helping!

I've attached both files:

[_models.zip](https://github.com/Micha95/homeassistant_timetree_calendar/files/7965780/_models.zip)

Maybe I made a mistake while copy/pasting? 

Thanks

**Comment by llewellynhughes** [comment]
@necroxysONE 

I think i can see the issue. Github has removed my underscores from my comment before and after the word init at the beginning of the class. If you look at the other def classes in that file, you should see the double underscore before and after. Hope that makes sense, and if it does try updating that and hopefully that should solve it.

**Comment by necroxysONE** [comment]
THANK YOU!! That did the trick 👍 

Thanks for the fast response!
